# Generated by Django 4.2.6 on 2023-10-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodels',
            options={'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
    ]
